# Use the latest Ubuntu image as the base
FROM ubuntu:latest

# Update and upgrade APT packages
RUN apt-get update
RUN apt-get upgrade -y

# Set the default command to print "Hello, World!"
CMD echo "Hello, World!"

# Build the Docker Image: docker build -t my-ubuntu-image .
# Run the docker container:  Build the Docker Image
